<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Paciente;
use Carbon\Carbon;

class PacienteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pacientes = [
            [
                'nombre' => 'Juan',
                'apellido' => 'Pérez',
                'cedula' => '10000001',
                'fecha_nacimiento' => Carbon::create(1985, 5, 15),
                'genero' => 'M',
                'telefono' => '3001000001',
                'email' => 'juan.perez@email.com',
                'direccion' => 'Carrera 1 #10-20, Bogotá',
                'eps' => 'Sura',
                'alergias' => 'Penicilina, Mariscos',
                'medicamentos_actuales' => 'Omeprazol 20mg, Vitamina D',
                'antecedentes_medicos' => 'Hipertensión arterial, Diabetes tipo 2',
                'contacto_emergencia' => 'María Pérez',
                'telefono_emergencia' => '3001000002',
                'activo' => true,
            ],
            [
                'nombre' => 'María',
                'apellido' => 'García',
                'cedula' => '10000002',
                'fecha_nacimiento' => Carbon::create(1990, 8, 22),
                'genero' => 'F',
                'telefono' => '3001000003',
                'email' => 'maria.garcia@email.com',
                'direccion' => 'Calle 5 #15-30, Bogotá',
                'eps' => 'Compensar',
                'alergias' => 'Ninguna conocida',
                'medicamentos_actuales' => 'Anticonceptivos orales',
                'antecedentes_medicos' => 'Embarazo ectópico (2018)',
                'contacto_emergencia' => 'Carlos García',
                'telefono_emergencia' => '3001000004',
                'activo' => true,
            ],
            [
                'nombre' => 'Carlos',
                'apellido' => 'López',
                'cedula' => '10000003',
                'fecha_nacimiento' => Carbon::create(1978, 12, 10),
                'genero' => 'M',
                'telefono' => '3001000005',
                'email' => 'carlos.lopez@email.com',
                'direccion' => 'Avenida 7 #25-40, Bogotá',
                'eps' => 'Sanitas',
                'alergias' => 'Aspirina',
                'medicamentos_actuales' => 'Atorvastatina 20mg, Metformina 850mg',
                'antecedentes_medicos' => 'Infarto de miocardio (2020), Colesterol alto',
                'contacto_emergencia' => 'Ana López',
                'telefono_emergencia' => '3001000006',
                'activo' => true,
            ],
            [
                'nombre' => 'Ana',
                'apellido' => 'Rodríguez',
                'cedula' => '10000004',
                'fecha_nacimiento' => Carbon::create(2005, 3, 18),
                'genero' => 'F',
                'telefono' => '3001000007',
                'email' => 'ana.rodriguez@email.com',
                'direccion' => 'Carrera 12 #8-15, Bogotá',
                'eps' => 'Coomeva',
                'alergias' => 'Lácteos',
                'medicamentos_actuales' => 'Ninguno',
                'antecedentes_medicos' => 'Asma infantil',
                'contacto_emergencia' => 'Luis Rodríguez',
                'telefono_emergencia' => '3001000008',
                'activo' => true,
            ],
            [
                'nombre' => 'Luis',
                'apellido' => 'Martínez',
                'cedula' => '10000005',
                'fecha_nacimiento' => Carbon::create(1992, 7, 30),
                'genero' => 'M',
                'telefono' => '3001000009',
                'email' => 'luis.martinez@email.com',
                'direccion' => 'Calle 20 #12-25, Bogotá',
                'eps' => 'Sura',
                'alergias' => 'Polvo, Ácaros',
                'medicamentos_actuales' => 'Loratadina 10mg',
                'antecedentes_medicos' => 'Rinitis alérgica crónica',
                'contacto_emergencia' => 'Carmen Martínez',
                'telefono_emergencia' => '3001000010',
                'activo' => true,
            ],
            [
                'nombre' => 'Carmen',
                'apellido' => 'Sánchez',
                'cedula' => '10000006',
                'fecha_nacimiento' => Carbon::create(1988, 11, 5),
                'genero' => 'F',
                'telefono' => '3001000011',
                'email' => 'carmen.sanchez@email.com',
                'direccion' => 'Avenida 15 #30-45, Bogotá',
                'eps' => 'Compensar',
                'alergias' => 'Ninguna',
                'medicamentos_actuales' => 'Levotiroxina 50mcg',
                'antecedentes_medicos' => 'Hipotiroidismo',
                'contacto_emergencia' => 'Roberto Sánchez',
                'telefono_emergencia' => '3001000012',
                'activo' => true,
            ],
            [
                'nombre' => 'Roberto',
                'apellido' => 'Hernández',
                'cedula' => '10000007',
                'fecha_nacimiento' => Carbon::create(1975, 4, 12),
                'genero' => 'M',
                'telefono' => '3001000013',
                'email' => 'roberto.hernandez@email.com',
                'direccion' => 'Carrera 8 #22-35, Bogotá',
                'eps' => 'Sanitas',
                'alergias' => 'Sulfitos',
                'medicamentos_actuales' => 'Losartán 50mg, Hidroclorotiazida 25mg',
                'antecedentes_medicos' => 'Hipertensión arterial, Enfermedad renal crónica',
                'contacto_emergencia' => 'Patricia Hernández',
                'telefono_emergencia' => '3001000014',
                'activo' => true,
            ],
            [
                'nombre' => 'Patricia',
                'apellido' => 'Morales',
                'cedula' => '10000008',
                'fecha_nacimiento' => Carbon::create(1998, 9, 25),
                'genero' => 'F',
                'telefono' => '3001000015',
                'email' => 'patricia.morales@email.com',
                'direccion' => 'Calle 18 #5-20, Bogotá',
                'eps' => 'Coomeva',
                'alergias' => 'Ninguna conocida',
                'medicamentos_actuales' => 'Ninguno',
                'antecedentes_medicos' => 'Sin antecedentes relevantes',
                'contacto_emergencia' => 'Fernando Morales',
                'telefono_emergencia' => '3001000016',
                'activo' => true,
            ],
            [
                'nombre' => 'Fernando',
                'apellido' => 'Ruiz',
                'cedula' => '10000009',
                'fecha_nacimiento' => Carbon::create(1982, 6, 8),
                'genero' => 'M',
                'telefono' => '3001000017',
                'email' => 'fernando.ruiz@email.com',
                'direccion' => 'Avenida 10 #18-30, Bogotá',
                'eps' => 'Sura',
                'alergias' => 'Penicilina',
                'medicamentos_actuales' => 'Sertralina 50mg',
                'antecedentes_medicos' => 'Depresión mayor, Ansiedad generalizada',
                'contacto_emergencia' => 'Sofia Ruiz',
                'telefono_emergencia' => '3001000018',
                'activo' => true,
            ],
            [
                'nombre' => 'Sofia',
                'apellido' => 'Díaz',
                'cedula' => '10000010',
                'fecha_nacimiento' => Carbon::create(1995, 1, 20),
                'genero' => 'F',
                'telefono' => '3001000019',
                'email' => 'sofia.diaz@email.com',
                'direccion' => 'Carrera 6 #14-25, Bogotá',
                'eps' => 'Compensar',
                'alergias' => 'Ninguna',
                'medicamentos_actuales' => 'Ninguno',
                'antecedentes_medicos' => 'Sin antecedentes relevantes',
                'contacto_emergencia' => 'Miguel Díaz',
                'telefono_emergencia' => '3001000020',
                'activo' => true,
            ],
        ];

        foreach ($pacientes as $paciente) {
            Paciente::create($paciente);
        }
    }
}